version: 0.2

env:
  shell: bash

phases:
  build:
    commands:
      - echo "Removing from S3"
      # HEAD_REF is refs/heads/BRANCH_NAME
      - BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -d "/" -f 3)
      - aws s3 rm s3://poc-aws-cdk/portal-system/$BRANCH_NAME --recursive