version: 0.2

env:
  shell: bash
  # secrets-manager:
  #   GITHUB_PASSWORD: GITHUB_PACKAGES:PASSWORD
  #   GITHUB_ACCOUNT: GITHUB_PACKAGES:ACCOUNT

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      # - echo "Setting npm config"
      # - npm config set @eleven-software:registry https://npm.pkg.github.com
      # - npm config set //npm.pkg.github.com/:_authToken $GITHUB_PASSWORD
      # - npm config set always-auth=true

      - echo "Installing dependencies"
      - npm ci

      # - echo "Running eslint"
      # - npm run lint

      - echo "Running tests"
      - npm run test

      - touch .env.production && echo REACT_APP_APPLICATION_VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION >> .env.production

      - echo "Building the project"
      - npm run build

      - echo "Copying build to S3"
      - aws s3 cp build s3://poc-aws-cdk/portal-system/$CODEBUILD_WEBHOOK_BASE_REF --recursive

      - echo "Invalidating couldfront"
      - aws cloudfront create-invalidation --distribution-id=$CLOUDFRONT_DISTRO_ID --paths '/*'

artifacts:
  base-directory: ./build
  files:
    - "**/*"

cache:
  paths:
    - "./node_modules/**/*"
