version: 0.2

env:
  shell: bash

phases:
  build:
    commands:
      # REFs are refs/heads/BRANCH_NAME
      - BASE_BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_BASE_REF | cut -d "/" -f 3)
      - HEAD_BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -d "/" -f 3)

      - echo "Promoting HEAD to BASE in S3"
      - aws s3 mv s3://poc-aws-cdk/portal-system/$HEAD_BRANCH_NAME s3://poc-aws-cdk/portal-system/$BASE_BRANCH_NAME --recursive