version: 0.2

env:
  shell: bash
  # secrets-manager:
  #   GITHUB_PASSWORD: GITHUB_PACKAGES:PASSWORD
  #   GITHUB_ACCOUNT: GITHUB_PACKAGES:ACCOUNT

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      # - echo "Setting npm config"
      # - npm config set @eleven-software:registry https://npm.pkg.github.com
      # - npm config set //npm.pkg.github.com/:_authToken $GITHUB_PASSWORD
      # - npm config set always-auth=true

      - echo "Installing dependencies"
      - npm ci

      # - echo "Running eslint"
      # - npm run lint

      - echo "Running tests"
      - npm run test

      - echo "Building the project"
      - npm run build

      # refs/heads/BRANCH_NAME -> BRANCH_NAME
      - BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | sed 's/refs\/heads\///')
      - echo "Copying build to S3 ($BRANCH_NAME)"
      - aws s3 sync build s3://$S3_BUCKET/$GITHUB_REPO/$BRANCH_NAME --acl public-read

      - echo "Invalidating couldfront ($CLOUDFRONT_DISTRO_ID)"
      - aws cloudfront create-invalidation --distribution-id=$CLOUDFRONT_DISTRO_ID --paths '/$GITHUB_REPO/*'

artifacts:
  base-directory: ./build
  files:
    - "**/*"

cache:
  paths:
    - "./node_modules/**/*"
