version: 0.2

env:
  shell: bash

phases:
  build:
    commands:
      - echo "Setting environment variables"
      # CODEBUILD_WEBHOOK_HEAD_REF=refs/heads/BRANCH_NAME, extract BRANCH_NAME
      - BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | sed 's|refs/heads/||') && echo "BRANCH_NAME=$BRANCH_NAME"

      - echo "Removing branch from s3"
      - APP_S3_BUCKET=s3://$S3_BUCKET/$GITHUB_REPO/$BRANCH_NAME && echo "APP_S3_BUCKET=$APP_S3_BUCKET"
      - aws s3 rm $APP_S3_BUCKET --recursive
