version: 0.2

env:
  shell: bash
  # secrets-manager:
  #   GITHUB_PASSWORD: GITHUB_PACKAGES:PASSWORD
  #   GITHUB_ACCOUNT: GITHUB_PACKAGES:ACCOUNT

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo "Setting environment variables"
      # CODEBUILD_WEBHOOK_HEAD_REF=refs/heads/BRANCH_NAME, extract BRANCH_NAME
      - BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | sed 's|refs/heads/||') && echo "BRANCH_NAME=$BRANCH_NAME"
      # - S3_BUCKET=s3://$S3_BUCKET/$GITHUB_REPO/$BRANCH_NAME && echo "S3_BUCKET=$S3_BUCKET"
      - PUBLIC_URL=https://$DOMAIN/$GITHUB_REPO/$BRANCH_NAME && echo "PUBLIC_URL=$PUBLIC_URL"

      # - echo "Setting npm config"
      # - npm config set @eleven-software:registry https://npm.pkg.github.com
      # - npm config set //npm.pkg.github.com/:_authToken $GITHUB_PASSWORD
      # - npm config set always-auth=true

      - echo "Installing dependencies"
      - npm ci

      # - echo "Running eslint"
      # - npm run lint

      # - echo "Running tests"
      # - npm run test

      - echo "Building the project ($PUBLIC_URL)"
      - npm run build

      - echo "copying app builds to s3"
      - for APP in $APPS;
        do
        S3_BUCKET=s3://$S3_BUCKET/$GITHUB_REPO/$BRANCH_NAME/$APP && echo "S3_BUCKET=$S3_BUCKET";
        aws s3 sync build $S3_BUCKET --acl public-read;
        done

      - echo "Invalidating couldfront ($CLOUDFRONT_DISTRO_ID)"
      - aws cloudfront create-invalidation --distribution-id=$CLOUDFRONT_DISTRO_ID --paths "/$GITHUB_REPO/$BRANCH_NAME/*"

artifacts:
  base-directory: ./build
  files:
    - "**/*"

cache:
  paths:
    - "./node_modules/**/*"
